version: '3'
services:
  na-registry:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-registry
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8761:8761
  phpmyadmin:
    environment:
      - PMA_HOSTS=${MYSQL_HOST}
    image: phpmyadmin/phpmyadmin
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 4000:80
networks:
  default:
    external:
      name: "na-network"
