version: '3.5'
services:
  na-pma:
    environment:
      - PMA_HOSTS=na-database
    image: phpmyadmin/phpmyadmin
    links:
      - na-database:db
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 4000:80
  na-database:
    image: mysql:5.7.30
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ~/na/db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  na-registry:
    image: ghcr.io/news-aggregator-bot/artifactory/bepicky.na-registry
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8761:8761
networks:
  default:
    external:
      name: picky
