version: '3'
services:
  na-registry:
    build: na-registry
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-registry
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8761:8761
networks:
  default:
    external:
      name: "na-network"
